In [1]:
track_progress = False
# If true, the model prints statements as it completes certain long calculations

# Specify tax reform

In [2]:
btax_dict1 = {
    2019: {
        'tau_c': 0.0,
        'tau_amt': 0.0,
    }
}
btax_dict2 = {}
# Dictionary for reforms to the individual tax code
ubi_under18 = 250 * 52
ubi_above18 = 500 * 52
iit_params_ref = {
    2019: {'_SS_thd50': [[0., 0., 0., 0., 0.]],
           '_SS_thd85': [[50000, 100000, 50000, 50000, 100000]],
           '_ALD_StudentLoan_hc': [1.0],
           '_ALD_SelfEmploymentTax_hc': [1.0],
           '_ALD_SelfEmp_HealthIns_hc': [1.0],
           '_ALD_KEOGH_SEP_hc': [1.0],
           '_ALD_EarlyWithdraw_hc': [1.0],
           '_ALD_AlimonyPaid_hc': [1.0],
           '_ALD_AlimonyReceived_hc': [1.0],
           '_ALD_EducatorExpenses_hc': [1.0],
           '_ALD_HSADeduction_hc': [1.0],
           '_ALD_IRAContributions_hc': [1.0],
           '_ALD_Tuition_hc': [1.0],
           '_ALD_BusinessLosses_c': [[0., 0., 0., 0., 0.]],
           '_STD': [[0., 0., 0., 0., 0.,]],
           '_STD_Aged': [[0., 0., 0., 0., 0.]],
           '_CDCC_c': [0.],
           '_CTC_c': [0.],
           '_DependentCredit_Child_c': [0.],
           '_DependentCredit_Nonchild_c': [0.],
           '_CR_RetirementSavings_hc': [1.0],
           '_CR_ForeignTax_hc': [1.0],
           '_CR_ResidentialEnergy_hc': [1.0],
           '_CR_GeneralBusiness_hc': [1.0],
           '_CR_MinimumTax_hc': [1.0],
           '_CR_AmOppRefundable_hc': [1.0],
           '_CR_AmOppNonRefundable_hc': [1.0],
           '_CR_SchR_hc': [1.0],
           '_CR_OtherCredits_hc': [1.0],
           '_CR_Education_hc': [1.0],
           '_ID_c': [[0., 0., 0., 0., 0.]],
           '_CG_brk1': [[50000, 100000, 50000, 50000, 100000]],
           '_CG_rt1': [.1],
           '_CG_brk2': [[9e99, 9e99, 9e99, 9e99, 9e99]],
           '_CG_rt2': [.45],
           '_CG_rt3': [.45],
           '_CG_nodiff': [True],
           '_II_brk1': [[50000, 100000, 50000, 50000, 100000]],
           '_II_rt2': [.45],
           '_II_brk2': [[50000, 100000, 50000, 50000, 100000]],
           '_II_rt3': [.45],
           '_II_brk3': [[50000, 100000, 50000, 50000, 100000]],
           '_II_rt4': [.45],
           '_II_brk4': [[50000, 100000, 50000, 50000, 100000]],
           '_II_rt5': [.45],
           '_II_brk5': [[50000, 100000, 50000, 50000, 100000]],
           '_II_rt6': [.45],
           '_II_brk6': [[50000, 100000, 50000, 50000, 100000]],
           '_II_rt7': [.45],
           '_PT_brk1': [[50000, 100000, 50000, 50000, 100000]],
           '_PT_rt2': [.45],
           '_PT_brk2': [[50000, 100000, 50000, 50000, 100000]],
           '_PT_rt3': [.45],
           '_PT_brk3': [[50000, 100000, 50000, 50000, 100000]],
           '_PT_rt4': [.45],
           '_PT_brk4': [[50000, 100000, 50000, 50000, 100000]],
           '_PT_rt5': [.45],
           '_PT_brk5': [[50000, 100000, 50000, 50000, 100000]],
           '_PT_rt6': [.45],
           '_PT_brk6': [[50000, 100000, 50000, 50000, 100000]],
           '_PT_rt7': [.45],
           '_PT_excl_rt': [0.0],
           '_AMT_rt1': [0.0],
           '_AMT_rt2': [0.0],
           '_NIIT_rt': [0.0],
           '_EITC_c': [[0., 0., 0., 0.]],
           '_UBI_u18': [ubi_under18],
           '_UBI_1820': [ubi_above18],
           '_UBI_21': [ubi_above18],
           '_BEN_housing_repeal': [True],
           '_BEN_ssi_repeal': [True],
           '_BEN_snap_repeal': [True],
           '_BEN_tanf_repeal': [True],
           '_BEN_vet_repeal': [True],
           '_BEN_wic_repeal': [True],
           '_BEN_mcare_repeal': [True],
           '_BEN_mcaid_repeal': [True],
           '_BEN_oasdi_repeal': [True],
           '_BEN_ui_repeal': [True],
           '_BEN_other_repeal': [True],
           '_SS_percentage1': [.1],
           '_SS_percentage2': [.5],
           '_STD_Dep': [0.0],
           '_LLC_Expense_c': [0.0],
           '_ETC_pe_Single': [0.0],
           '_ETC_pe_Married': [0.0]},
    2026: {'_ALD_DomesticProduction_hc': [1.0],
           '_II_em': [0.],
           '_ID_Miscellaneous_hc': [1.0]}
}
elast_dict = {}
exec(open('run_brc.py').read())

You loaded data for 2011.
Tax-Calculator startup automatically extrapolated your data to 2013.
All parameters updated
Reform corporate tax revenue complete
You loaded data for 2011.
Tax-Calculator startup automatically extrapolated your data to 2013.
You loaded data for 2011.
Tax-Calculator startup automatically extrapolated your data to 2013.

# Generate the new baseline, where/when appropriate

In [3]:
exec(open('gen_baseline.py').read())

You loaded data for 2011.
Tax-Calculator startup automatically extrapolated your data to 2013.

# Check the results

### Check final results

In [4]:
compare = np.asarray(combined_ref['taxrev'] - combined_base['taxrev'])

print("Total corporate tax revenue change, 2014-2027: " + str(np.round(sum(compare), 3)))
print("Total corporate tax revenue change, 2017-2026: " + str(np.round(sum(compare[3:13]), 3)))
print("Total corporate tax revenue change, 2018-2027: " + str(np.round(sum(compare[4:]), 3)))

Total corporate tax revenue change, 2014-2027: -4174.946
Total corporate tax revenue change, 2017-2026: -3668.829
Total corporate tax revenue change, 2018-2027: -4174.946

In [5]:
ModelResults

    year   IndivTaxRev    CorpTaxRev  RevenueChange
0   2014  5.337655e-14  0.000000e+00   5.337655e-14
1   2015  8.425402e-14  0.000000e+00   8.425402e-14
2   2016  3.458049e-14  0.000000e+00   3.458049e-14
3   2017  2.091800e-13  0.000000e+00   2.091800e-13
4   2018  5.825827e-14  5.684342e-14   1.151017e-13
5   2019  3.953730e+03 -4.325091e+02   3.521221e+03
6   2020  4.104982e+03 -4.654418e+02   3.639540e+03
7   2021  4.229428e+03 -4.512281e+02   3.778200e+03
8   2022  4.371107e+03 -4.465338e+02   3.924574e+03
9   2023  4.519518e+03 -4.522779e+02   4.067240e+03
10  2024  4.676135e+03 -4.606522e+02   4.215483e+03
11  2025  4.839655e+03 -4.720190e+02   4.367636e+03
12  2026  4.781168e+03 -4.881676e+02   4.293001e+03
13  2027  4.953134e+03 -5.061169e+02   4.447017e+03

In [6]:
print("Total tax revenue change, 2014-2027: " + str(np.round(sum(ModelResults['RevenueChange']), 3)))
print("Total tax revenue change, 2017-2026: " + str(np.round(sum(ModelResults['RevenueChange'][3:13]), 3)))
print("Total tax revenue change, 2018-2027: " + str(np.round(sum(ModelResults['RevenueChange'][4:]), 3)))

Total tax revenue change, 2014-2027: 36253.913
Total tax revenue change, 2017-2026: 31806.896
Total tax revenue change, 2018-2027: 36253.913

# Individual Reforms

In [7]:
from bokeh.io import export_png

In [8]:
taxcalc.__version__

'0.22.2'

In [9]:
target_year = 2019
# CPS based calculators for benefit analysis
welfare_multiples = {
    2019: {
        '_BEN_vet_value': [0.95],
        '_BEN_mcare_value': [0.75],
        '_BEN_mcaid_value': [0.30]
    }
}
behavior_reform = {
    2019: {
        '_BE_sub': [0.25]
    }
}
consumption = taxcalc.Consumption()
consumption.update_consumption(welfare_multiples)
calc_cps_base = taxcalc.Calculator(records=taxcalc.Records.cps_constructor(),
                                   policy=taxcalc.Policy(),
                                   consumption=consumption)
# reform  calculator
pol = taxcalc.Policy()
pol.implement_reform(iit_params_ref)
calc_cps_reform = taxcalc.Calculator(records=taxcalc.Records.cps_constructor(),
                                     policy=pol,
                                     consumption=consumption)

# PUF based calculators for tax analysis
calc_puf_base = taxcalc.Calculator(records=taxcalc.Records(), policy=taxcalc.Policy())
calc_puf_base.advance_to_year(target_year)
behav = taxcalc.Behavior()
behav.update_behavior(behavior_reform)
calc_puf_temp = taxcalc.Calculator(records=taxcalc.Records(), policy=pol, behavior=behav)
calc_puf_temp.advance_to_year(target_year)
calc_puf_reform = taxcalc.Behavior.response(calc_puf_base, calc_puf_temp)

You loaded data for 2014.
Tax-Calculator startup automatically extrapolated your data to 2014.
You loaded data for 2014.
Tax-Calculator startup automatically extrapolated your data to 2014.
You loaded data for 2011.
Tax-Calculator startup automatically extrapolated your data to 2013.
You loaded data for 2011.
Tax-Calculator startup automatically extrapolated your data to 2013.

In [10]:
var_list = ['aftertax_income', 'benefit_cost_total', 'benefit_value_total',
            'c00100', 'c04800', 'combined', 's006', 'ubi', 'expanded_income']
calc_cps_base.advance_to_year(target_year)
calc_cps_base.calc_all()
calc_cps_reform.advance_to_year(target_year)
calc_cps_reform.calc_all()

# calc_puf_base.advance_to_year(target_year)
# calc_puf_base.calc_all()
# calc_puf_reform.advance_to_year(target_year)
# calc_puf_reform.calc_all()

base_cps_data = calc_cps_base.dataframe(var_list)
reform_cps_data = calc_cps_reform.dataframe(var_list)
base_puf_data = calc_puf_base.dataframe(var_list)
reform_puf_data = calc_puf_reform.dataframe(var_list)

mtr_plot = calc_puf_base.mtr_graph(calc_puf_reform)
pch_plot = calc_puf_base.pch_graph(calc_puf_reform)
decile_plot = calc_puf_base.decile_graph(calc_puf_reform)
export_png(mtr_plot, filename='mtr_2019_2.png')
export_png(pch_plot, filename='pch_2019_2.png')
export_png(decile_plot, filename='decile_2019_2.png')

cps_mtrs = calc_cps_reform.mtr()
puf_mtrs = calc_puf_reform.mtr()

## 2019
![title](decile_2019_2.png)
![title](mtr_2019_2.png)
![title](pch_2019_2.png)

In [11]:
def table_values(data, var):
    """
    Function to return the values for each table
    """
    val = data.groupby('bins', as_index=False).apply(weighted_mean, var)
    return val


def table(data, income_measure, bins=None):
    """
    Function to create a table
    Parameters
    ----------
    data: DataFrame containing data from Tax-Calculator
    income_measure: income used for binning
    bins: number of desired bins
    labels: bin labels
    """

    # add bin labels
    data['bins'] = pd.cut(data[income_measure], bins, include_lowest=True)
    floors = []
    for _bin in np.unique(data['bins']):
        floor = min(data[income_measure][data['bins'] == _bin])
        floors.append(floor)
    decile_floor = pd.Series(floors)

    # find values for table
    # average tax unit size
    avg_size = table_values(data, 'ppl')
    # average UBI per person
    avg_ubi_person = table_values(data, 'ubi/person')
    # average payroll MTR
    avg_pmtr = table_values(data, 'pmtr')
    # average income tax MTR
    avg_imtr = table_values(data, 'imtr')
    # average combined MTR
    avg_cmtr = table_values(data, 'cmtr')
    # average tax change
    avg_tax_change = table_values(data, 'tax_change')
    # average UBI per tax unit
    avg_ubi = table_values(data, 'ubi')
    # average benefit change
    avg_ben = table_values(data, 'ben_change')
    # average benefit change - welfare adjusted
    avg_ben_welfare = table_values(data, 'ben_change_welfare')
    # average combined change
    avg_combined = table_values(data, 'combined_change')
    # average combined change - welfare adjusted
    avg_combined_welfare = table_values(data, 'combined_change_welfare')
    # tax units in a bin
    units = data.groupby('bins', as_index=False).sum()['s006']

    # Create DataFrame with all relevant information
    info = pd.DataFrame()
    if income_measure == 'e00200':
        income_str = 'Wage and Salary Floor (Thousands)'
    elif income_measure == 'c00100':
        income_str = 'AGI Floor (Thousands)'
    else:
        income_str = 'Income Floor (Thousands)'
    info[income_str] = (decile_floor / 1000).apply('{:,.0f}'.format)
    info['Tax Units (m)'] = (units / 1000000).apply('{:,.2f}'.format)
    info['Avg Tax Unit Size'] = avg_size.apply('{:,.2f}'.format)
    info['Avg UBI Per Person'] = avg_ubi_person
    info['Avg MTR - Payroll'] = (avg_pmtr * 100).apply('{:.1f}%'.format)
    info['Avg MTR - Individual Income'] = (avg_imtr *
                                           100).apply('{:.1f}%'.format)
    info['Avg MTR - Combined'] = (avg_cmtr * 100).apply('{:.1f}%'.format)
    info['Avg Tax Change'] = avg_tax_change
    info['Avg UBI Per Tax Unit'] = avg_ubi
    info['Avg Benefits Change'] = avg_ben
    info['Avg Benefits Change - Welfare Adj'] = avg_ben_welfare
    info['Avg Combined Change'] = avg_combined
    info['Avg Combined Change - Welfare Adj'] = avg_combined_welfare

    return info

In [12]:
# create a table from the CPS data
cps_table_data = calc_cps_base.dataframe(['elderly_dependents', 'age_head',
                                          'age_spouse', 'e00200', 's006',
                                          'nu18', 'n1820', 'n21'])
cps_table_data['expanded_income'] = base_cps_data['expanded_income']
cps_table_data['ppl'] = cps_table_data['nu18'] + cps_table_data['n1820'] + cps_table_data['n21']
cps_table_data['ubi'] = reform_cps_data['ubi']
cps_table_data['ubi/person'] = cps_table_data['ubi'] / cps_table_data['ppl']
cps_tax_change = calc_cps_reform.array('combined') - calc_cps_base.array('combined')
cps_table_data['tax_change'] = cps_tax_change
cps_ben_change = (calc_cps_reform.array('benefit_cost_total') -
                  calc_cps_base.array('benefit_cost_total'))
cps_table_data['ben_change'] = cps_ben_change
cps_ben_change_welfare = (calc_cps_reform.array('benefit_value_total') -
                          calc_cps_base.array('benefit_value_total'))
cps_table_data['ben_change_welfare'] = cps_ben_change_welfare
cps_combined_change = (cps_table_data['ubi'] -
                       cps_table_data['tax_change'] +
                       cps_table_data['ben_change'])
cps_table_data['combined_change'] = cps_combined_change
cps_combined_change_welfare = (cps_table_data['ubi'] -
                               cps_table_data['tax_change'] +
                               cps_table_data['ben_change_welfare'])
cps_table_data['combined_change_welfare'] = cps_combined_change_welfare
cps_table_data['65_plus'] = np.where((cps_table_data['elderly_dependents'] == 1) |
                                     (cps_table_data['age_head'] >= 65) |
                                     (cps_table_data['age_spouse']), 1, 0)
cps_table_data['pmtr'] = cps_mtrs[0]
cps_table_data['imtr'] = cps_mtrs[1]
cps_table_data['cmtr'] = cps_mtrs[2]

# create a table from PUF data
puf_table_data = calc_puf_base.dataframe(['elderly_dependents', 'age_head',
                                          'age_spouse', 'e00200', 's006',
                                          'nu18', 'n1820', 'n21'])
puf_table_data['expanded_income'] = base_puf_data['expanded_income']
puf_table_data['ppl'] = puf_table_data['nu18'] + puf_table_data['n1820'] + puf_table_data['n21']
puf_table_data['ubi'] = reform_puf_data['ubi']
puf_table_data['ubi/person'] = puf_table_data['ubi'] / puf_table_data['ppl']
puf_tax_change = calc_puf_reform.array('combined') - calc_puf_base.array('combined')
puf_table_data['tax_change'] = puf_tax_change
puf_ben_change = (calc_puf_reform.array('benefit_cost_total') -
                  calc_puf_base.array('benefit_cost_total'))
puf_table_data['ben_change'] = puf_ben_change
puf_ben_change_welfare = (calc_puf_reform.array('benefit_value_total') -
                          calc_puf_base.array('benefit_value_total'))
puf_table_data['ben_change_welfare'] = puf_ben_change_welfare
puf_combined_change = (puf_table_data['ubi'] -
                       puf_table_data['tax_change'] +
                       puf_table_data['ben_change'])
puf_table_data['combined_change'] = puf_combined_change
puf_combined_change_welfare = (puf_table_data['ubi'] -
                               puf_table_data['tax_change'] +
                               puf_table_data['ben_change_welfare'])
puf_table_data['combined_change_welfare'] = puf_combined_change_welfare
puf_table_data['65_plus'] = np.where((puf_table_data['elderly_dependents'] == 1) |
                                     (puf_table_data['age_head'] >= 65) |
                                     (puf_table_data['age_spouse']), 1, 0)
puf_table_data['pmtr'] = puf_mtrs[0]
puf_table_data['imtr'] = puf_mtrs[1]
puf_table_data['cmtr'] = puf_mtrs[2]


income_bins = [0, 9999, 19999, 29999, 39999, 49999,
               74999, 99999, 199999, 1000000, 9e99]

In [13]:
cps_table = table(cps_table_data, 'e00200', income_bins)
puf_table = table(puf_table_data, 'e00200', income_bins)

In [14]:
cps_drop_cols = ['Avg MTR - Payroll', 'Avg MTR - Individual Income', 'Avg MTR - Combined',
                 'Tax Units (m)', 'Avg Tax Change', 'Avg Tax Unit Size',
                 'Avg Combined Change', 'Avg Combined Change - Welfare Adj']
cps_table.drop(cps_drop_cols, axis=1, inplace=True)
cps_table

,Wage and Salary Floor (Thousands),Avg UBI Per Person,Avg UBI Per Tax Unit,Avg Benefits Change,Avg Benefits Change - Welfare Adj
0,0,24680.328590,39100.193393,-35178.447457,-30174.757106
1,10,23951.367345,41189.127797,-16171.312535,-12389.249500
2,20,23990.771350,41725.203350,-12308.907990,-9228.826981
3,30,24018.520508,43179.365923,-10386.542228,-7754.431322
4,40,23985.297626,44956.691052,-9545.686203,-7286.079629
5,50,23934.312205,47746.354714,-8650.192970,-6890.555560
6,75,23659.566500,53423.513481,-7293.388741,-5894.465403
7,100,23287.128240,60230.224959,-6621.008108,-5515.679349
8,200,23108.311518,64188.340559,-5386.447995,-4438.580373
9,"1,000",23073.196747,62183.666065,-5947.932300,-4932.704402

In [15]:
puf_drop_cols = ['Avg UBI Per Tax Unit', 'Avg Benefits Change', 'Avg Benefits Change - Welfare Adj',
                 'Avg Combined Change', 'Avg Combined Change - Welfare Adj', 'Avg UBI Per Person']
puf_table.drop(puf_drop_cols, axis=1, inplace=True)
puf_table

,Wage and Salary Floor (Thousands),Tax Units (m),Avg Tax Unit Size,Avg MTR - Payroll,Avg MTR - Individual Income,Avg MTR - Combined,Avg Tax Change
0,0,72.90,1.55,14.2%,18.7%,32.9%,9075.745895
1,10,15.75,1.74,14.2%,21.8%,36.0%,10443.416834
2,20,13.39,1.92,14.2%,31.8%,46.0%,13113.397816
3,30,11.39,2.01,14.2%,39.0%,53.2%,15541.103580
4,40,10.07,2.00,14.2%,39.7%,53.9%,17463.096304
5,50,17.18,2.09,14.2%,41.5%,55.7%,21246.532036
6,75,10.20,2.36,14.2%,41.8%,55.9%,28617.351244
7,100,18.00,2.79,12.4%,42.0%,54.5%,42328.782010
8,200,6.14,3.03,8.1%,43.2%,51.3%,86355.164369
9,"1,000",0.23,3.24,6.7%,43.7%,50.4%,424409.520308

In [16]:
# Create the final table
final_table = puf_table.merge(cps_table, on='Wage and Salary Floor (Thousands)')
final_table['Avg Combined Change'] = (final_table[['Avg UBI Per Tax Unit', 'Avg Benefits Change']].sum(axis=1) -
                                      final_table['Avg Tax Change'])
final_table['Avg Combined Change - Welfare Adj'] = (final_table[['Avg UBI Per Tax Unit', 'Avg Benefits Change - Welfare Adj']].sum(axis=1) -
                                                    final_table['Avg Tax Change'])
final_table.style.format('${:,.2f}', subset=['Avg Tax Change', 'Avg UBI Per Tax Unit', 'Avg UBI Per Person',
                                            'Avg Benefits Change', 'Avg Benefits Change - Welfare Adj',
                                            'Avg Combined Change', 'Avg Combined Change - Welfare Adj'])

In [17]:
# total results
ind_inc_change = (puf_table_data['tax_change'] * puf_table_data['s006']).sum()
corp_change = (ModelResults['CorpTaxRev'][ModelResults['year'] == 2019] * 1e9).values[0]
ben_loss = (cps_table_data['ben_change'] * cps_table_data['s006']).sum()
ben_loss_welfare = (cps_table_data['ben_change_welfare'] * cps_table_data['s006']).sum()
ubi = (cps_table_data['ubi'] * cps_table_data['s006']).sum()
# welfare changes = ubi payments - tax change - benefit loss
combined_change = (ubi - ind_inc_change + ben_loss)
combined_change_welfare = (ubi - ind_inc_change + ben_loss_welfare)
ben_savings = ben_loss * -1  # multiply by -1 to get the invert the losses and get revenue
# revenue = tax revenue change + benefit repeal savings - ubi payments
rev_change = (ind_inc_change + corp_change + ben_savings - ubi)
print(f'Individual Tax Change:                 ${ind_inc_change:,.2f}')
print(f'Corporate Tax Change:                   ${corp_change:,.2f}')
print(f'Benefit Loss:                         ${ben_loss:,.2f}')
print(f'Benefit Loss - Welfare Adjusted:      ${ben_loss_welfare:,.2f}')
print(f'UBI:                                   ${ubi:,.2f}')
print('-' * 60)
print(f'Combined Change:                       ${combined_change:,.2f}')
print(f'Combined Change - Welfare Adjusted:    ${combined_change_welfare:,.2f}')
print('-' * 60)
print(f'Revenue Change:                       ${rev_change:,.2f}')

Individual Tax Change:                 $3,399,237,547,109.05
Corporate Tax Change:                   $-432,509,066,975.28
Benefit Loss:                         $-2,960,127,019,159.39
Benefit Loss - Welfare Adjusted:      $-2,450,549,797,004.65
UBI:                                   $7,549,061,722,930.00
------------------------------------------------------------
Combined Change:                       $1,189,697,156,661.57
Combined Change - Welfare Adjusted:    $1,699,274,378,816.30
------------------------------------------------------------
Revenue Change:                       $-1,622,206,223,636.85

In [18]:
params_dict = {'policy': iit_params_ref,
               'growdiff_baseline': {}}
print(calc_puf_reform.reform_documentation(params_dict))

REFORM DOCUMENTATION
Baseline Growth-Difference Assumption Values by Year:
none: using default baseline growth assumptions
Policy Reform Parameter Values by Year:
2019:
 _ALD_AlimonyPaid_hc : 1.0
  name: Adjustment for alimony-paid haircut
  desc: Under pre-TCJA law, the full amount of alimony paid is taken as an
        adjustment from gross income in arriving at AGI. This haircut can be
        used to change the deduction allowed.
  baseline_value: 1.0
 _ALD_AlimonyReceived_hc : 1.0
  name: Adjustment for alimony-received haircut
  desc: Under pre-TCJA law, none of alimony received is taken as an adjustment
        from gross income in arriving at AGI. This haircut can be used to
        change the deduction allowed.
  baseline_value: 0.0
 _ALD_BusinessLosses_c : [0.0, 0.0, 0.0, 0.0, 0.0]
                         ['single', 'joint', 'separate', 'headhousehold', 'widow']
  name: Maximum amount of business losses deductible
  desc: Business losses in excess of this amount may not be deducted from AGI.
  baseline_value: [254975.0, 509950.0, 254975.0, 254975.0, 509950.0]
 _ALD_EarlyWithdraw_hc : 1.0
  name: Adjustment for early withdrawal penalty haircut
  desc: Under current law, early withdraw penalty can be fully deducted from
        gross income. This haircut can be used to limit the adjustment
        allowed.
  baseline_value: 0.0
 _ALD_EducatorExpenses_hc : 1.0
  name: Deduction for educator expenses haircut
  desc: If greater than zero, this decimal fraction reduces the portion of
        educator expenses that can be deducted from AGI.
  baseline_value: 0.0
 _ALD_HSADeduction_hc : 1.0
  name: Deduction for HSA deduction haircut
  desc: If greater than zero, this decimal fraction reduces the portion of a
        taxpayer's HSA deduction that can be deducted from AGI.
  baseline_value: 0.0
 _ALD_IRAContributions_hc : 1.0
  name: Deduction for IRA contributions haircut
  desc: If greater than zero, this decimal fraction reduces the portion of IRA
        contributions that can be deducted from AGI.
  baseline_value: 0.0
 _ALD_KEOGH_SEP_hc : 1.0
  name: Adjustment for contributions to either KEOGH or SEP plan haircut
  desc: Under current law, contributions to Keogh or SEP plans can be fully
        deducted from gross income. This haircut can be used to limit the
        adjustment allowed.
  baseline_value: 0.0
 _ALD_SelfEmp_HealthIns_hc : 1.0
  name: Adjustment for self employed health insurance haircut
  desc: This decimal fraction, if greater than zero, reduces the health
        insurance adjustment for self-employed taxpayers.
  baseline_value: 0.0
 _ALD_SelfEmploymentTax_hc : 1.0
  name: Adjustment for self-employment tax haircut
  desc: This decimal fraction, if greater than zero, reduces the employer
        equivalent portion of self-employment adjustment.
  baseline_value: 0.0
 _ALD_StudentLoan_hc : 1.0
  name: Adjustment for student loan interest haircut
  desc: This decimal fraction can be applied to limit the student loan
        interest adjustment allowed.
  baseline_value: 0.0
 _ALD_Tuition_hc : 1.0
  name: Deduction for tuition and fees haircut
  desc: If greater than zero, this decimal fraction reduces the portion of
        tuition and fees that can be deducted from AGI.
  baseline_value: 0.0
 _AMT_rt1 : 0.0
  name: AMT rate 1
  desc: The tax rate applied to the portion of AMT taxable income below the
        surtax threshold, AMT bracket 1.
  baseline_value: 0.26
 _AMT_rt2 : 0.0
  name: Additional AMT rate for AMT taxable income above AMT bracket 1
  desc: The additional tax rate applied to the portion of AMT income above the
        AMT bracket 1.
  baseline_value: 0.02
 _BEN_housing_repeal : True
  name: Housing benefit repeal switch
  desc: Housing benefits can be repealed by switching this parameter to true.
  baseline_value: False
 _BEN_mcaid_repeal : True
  name: Medicaid benefit repeal switch
  desc: Medicaid benefits can be repealed by switching this parameter to true.
  baseline_value: False
 _BEN_mcare_repeal : True
  name: Medicare benefit repeal switch
  desc: Medicare benefits can be repealed by switching this parameter to true.
  baseline_value: False
 _BEN_oasdi_repeal : True
  name: Social Security benefit repeal switch
  desc: Social Security benefits (e02400) can be repealed by switching this
        parameter to true.
  baseline_value: False
 _BEN_other_repeal : True
  name: Other benefit repeal switch
  desc: Other benefits can be repealed by switching this parameter to true.
  baseline_value: False
 _BEN_snap_repeal : True
  name: SNAP benefit repeal switch
  desc: SNAP benefits can be repealed by switching this parameter to true.
  baseline_value: False
 _BEN_ssi_repeal : True
  name: SSI benefit repeal switch
  desc: SSI benefits can be repealed by switching this parameter to true.
  baseline_value: False
 _BEN_tanf_repeal : True
  name: TANF benefit repeal switch
  desc: TANF benefits can be repealed by switching this parameter to true.
  baseline_value: False
 _BEN_ui_repeal : True
  name: Unemployment insurance benefit repeal switch
  desc: Unemployment insurance benefits (e02300) can be repealed by switching
        this parameter to true.
  baseline_value: False
 _BEN_vet_repeal : True
  name: Veterans benefit repeal switch
  desc: Veterans benefits can be repealed by switching this parameter to true.
  baseline_value: False
 _BEN_wic_repeal : True
  name: WIC benefit repeal switch
  desc: WIC benefits can be repealed by switching this parameter to true.
  baseline_value: False
 _CDCC_c : 0.0
  name: Maximum child & dependent care credit per dependent
  desc: The maximum amount of credit allowed for each qualifying dependent.
  baseline_value: 3000.0
 _CG_brk1 : [50000, 100000, 50000, 50000, 100000]
            ['single', 'joint', 'separate', 'headhousehold', 'widow']
  name: Top of long-term capital gains and qualified dividends
        (regular/non-AMT) tax bracket 1
  desc: The gains and dividends (stacked on top of regular income) below this
        are taxed at capital gain rate 1.
  baseline_value: [39483.18, 78966.36, 39483.18, 52852.32, 78966.36]
 _CG_brk2 : [9e+99, 9e+99, 9e+99, 9e+99, 9e+99]
            ['single', 'joint', 'separate', 'headhousehold', 'widow']
  name: Top of long-term capital gains and qualified dividends
        (regular/non-AMT) tax bracket 2
  desc: The gains and dividends (stacked on top of regular income) below this
        and above top of bracket 1 are taxed at capital gain rate 2.
  baseline_value: [435303.36, 489716.28, 244858.14, 462509.82, 489716.28]
 _CG_nodiff : True
  name: Long term capital gains and qualified dividends taxed no differently
        than regular taxable income
  desc: Specifies whether or not long term capital gains and qualified
        dividends are taxed like regular taxable income.
  baseline_value: False
 _CG_rt1 : 0.1
  name: Long term capital gain and qualified dividends (regular/non-AMT) rate
        1
  desc: The capital gain and dividends (stacked on top of regular income) that
        are below threshold 1 are taxed at this rate.
  baseline_value: 0.0
 _CG_rt2 : 0.45
  name: Long term capital gain and qualified dividends (regular/non-AMT) rate
        2
  desc: The capital gain and dividends (stacked on top of regular income) that
        are below threshold 2 and above threshold 1 are taxed at this rate.
  baseline_value: 0.15
 _CG_rt3 : 0.45
  name: Long term capital gain and qualified dividends (regular/non-AMT) rate
        3
  desc: The capital gain and dividends (stacked on top of regular income) that
        are above threshold 2 and below threshold 3 are taxed at this rate.
  baseline_value: 0.2
 _CR_AmOppNonRefundable_hc : 1.0
  name: Nonrefundable portion of the American Opportunity Credit haircut
  desc: If greater than zero, this decimal fraction reduces the portion of the
        nonrefundable American Opportunity credit that can be claimed.
  baseline_value: 0.0
 _CR_AmOppRefundable_hc : 1.0
  name: Refundable portion of the American Opportunity Credit haircut
  desc: If greater than zero, this decimal fraction reduces the portion of the
        refundable American Opportunity credit that can be claimed.
  baseline_value: 0.0
 _CR_Education_hc : 1.0
  name: Education Credits haircut
  desc: If greater than zero, this decimal fraction reduces the portion of
        education credits that can be claimed.
  baseline_value: 0.0
 _CR_ForeignTax_hc : 1.0
  name: Credit for foreign tax haircut
  desc: If greater than zero, this decimal fraction reduces the portion of the
        foreign tax credit that can be claimed.
  baseline_value: 0.0
 _CR_GeneralBusiness_hc : 1.0
  name: Credit for general business haircut
  desc: If greater than zero, this decimal fraction reduces the portion of the
        general business credit that can be claimed.
  baseline_value: 0.0
 _CR_MinimumTax_hc : 1.0
  name: Credit for previous year minimum tax credit haircut
  desc: If greater than zero, this decimal fraction reduces the portion of the
        previous year minimum tax credit that can be claimed.
  baseline_value: 0.0
 _CR_OtherCredits_hc : 1.0
  name: Other Credits haircut
  desc: If greater than zero, this decimal fraction reduces the portion of
        other credit that can be claimed.
  baseline_value: 0.0
 _CR_ResidentialEnergy_hc : 1.0
  name: Credit for residential energy haircut
  desc: If greater than zero, this decimal fraction reduces the portion of the
        residential energy credit that can be claimed.
  baseline_value: 0.0
 _CR_RetirementSavings_hc : 1.0
  name: Credit for retirement savings haircut
  desc: If greater than zero, this decimal fraction reduces the portion of the
        retirement savings credit that can be claimed.
  baseline_value: 0.0
 _CR_SchR_hc : 1.0
  name: Schedule R Credit haircut
  desc: If greater than zero, this decimal fraction reduces the portion of
        Schedule R credit that can be claimed.
  baseline_value: 0.0
 _CTC_c : 0.0
  name: Maximum child tax credit per child
  desc: The maximum amount of credit allowed for each child.
  baseline_value: 1400.0
 _DependentCredit_Child_c : 0.0
  name: Nonrefundable credit for child dependents on top of the child tax
        credit
  desc: This nonrefundable credit is applied to child dependents and begins
        phasing out after the CTC phaseout ends.
  baseline_value: 600.0
 _DependentCredit_Nonchild_c : 0.0
  name: Nonrefundable credit for non-child dependents on top of the child tax
        credit
  desc: This nonrefundable credit is applied to non-child dependents and
        begins phasing out after the CTC phaseout ends.
  baseline_value: 500.0
 _EITC_c : [0.0, 0.0, 0.0, 0.0]
           ['0kids', '1kid', '2kids', '3+kids']
  name: Maximum earned income credit
  desc: This is the maximum amount of earned income credit taxpayers are
        eligible for; it depends on how many kids they have.
  baseline_value: [530.6, 3537.36, 5842.88, 6573.25]
 _ETC_pe_Married : 0.0
  name: Education tax credit phaseout ends (Married)
  desc: The education tax credit will be zero for those taxpayers of married
        filing status with modified AGI level (in thousands) higher than this
        level.
  baseline_value: 138.01
 _ETC_pe_Single : 0.0
  name: Education tax credit phaseout ends (Single)
  desc: The education tax credit will be zero for those taxpayers of single
        filing status with modified AGI (in thousands) higher than this level.
  baseline_value: 68.48
 _ID_c : [0.0, 0.0, 0.0, 0.0, 0.0]
         ['single', 'joint', 'separate', 'headhousehold', 'widow']
  name: Ceiling on the amount of itemized deductions allowed (dollars)
  desc: The amount of itemized deductions is limited to this dollar amount.
  baseline_value: [9e+99, 9e+99, 9e+99, 9e+99, 9e+99]
 _II_brk1 : [50000, 100000, 50000, 50000, 100000]
            ['single', 'joint', 'separate', 'headhousehold', 'widow']
  name: Personal income (regular/non-AMT/non-pass-through) tax bracket (upper
        threshold) 1
  desc: Taxable income below this threshold is taxed at tax rate 1.
  baseline_value: [9714.55, 19429.1, 9714.55, 13870.64, 19429.1]
 _II_brk2 : [50000, 100000, 50000, 50000, 100000]
            ['single', 'joint', 'separate', 'headhousehold', 'widow']
  name: Personal income (regular/non-AMT/non-pass-through) tax bracket (upper
        threshold) 2
  desc: Income below this threshold and above tax bracket 1 is taxed at tax
        rate 2.
  baseline_value: [39470.13, 78940.26, 39470.13, 52830.82, 78940.26]
 _II_brk3 : [50000, 100000, 50000, 50000, 100000]
            ['single', 'joint', 'separate', 'headhousehold', 'widow']
  name: Personal income (regular/non-AMT/non-pass-through) tax bracket (upper
        threshold) 3
  desc: Income below this threshold and above tax bracket 2 is taxed at tax
        rate 3.
  baseline_value: [84141.75, 168283.5, 84141.75, 84141.75, 168283.5]
 _II_brk4 : [50000, 100000, 50000, 50000, 100000]
            ['single', 'joint', 'separate', 'headhousehold', 'widow']
  name: Personal income (regular/non-AMT/non-pass-through) tax bracket (upper
        threshold) 4
  desc: Income below this threshold and above tax bracket 3 is taxed at tax
        rate 4.
  baseline_value: [160634.25, 321268.5, 160634.25, 160634.25, 321268.5]
 _II_brk5 : [50000, 100000, 50000, 50000, 100000]
            ['single', 'joint', 'separate', 'headhousehold', 'widow']
  name: Personal income (regular/non-AMT/non-pass-through) tax bracket (upper
        threshold) 5
  desc: Income below this threshold and above tax bracket 4 is taxed at tax
        rate 5.
  baseline_value: [203980.0, 407960.0, 203980.0, 203980.0, 407960.0]
 _II_brk6 : [50000, 100000, 50000, 50000, 100000]
            ['single', 'joint', 'separate', 'headhousehold', 'widow']
  name: Personal income (regular/non-AMT/non-pass-through) tax bracket 6
  desc: Income below this threshold and above tax bracket 5 is taxed at tax
        rate 6.
  baseline_value: [509950.0, 611940.0, 305970.0, 509950.0, 509950.0]
 _II_rt2 : 0.45
  name: Personal income (regular/non-AMT/non-pass-through) tax rate 2
  desc: The second lowest tax rate, applied to the portion of taxable income
        below tax bracket 2 and above tax bracket 1.
  baseline_value: 0.12
 _II_rt3 : 0.45
  name: Personal income (regular/non-AMT/non-pass-through) tax rate 3
  desc: The third lowest tax rate, applied to the portion of taxable income
        below tax bracket 3 and above tax bracket 2.
  baseline_value: 0.22
 _II_rt4 : 0.45
  name: Personal income (regular/non-AMT/non-pass-through) tax rate 4
  desc: The tax rate applied to the portion of taxable income below tax
        bracket 4 and above tax bracket 3.
  baseline_value: 0.24
 _II_rt5 : 0.45
  name: Personal income (regular/non-AMT/non-pass-through) tax rate 5
  desc: The third highest tax rate, applied to the portion of taxable income
        below tax bracket 5 and above tax bracket 4.
  baseline_value: 0.32
 _II_rt6 : 0.45
  name: Personal income (regular/non-AMT/non-pass-through) tax rate 6
  desc: The second higher tax rate, applied to the portion of taxable income
        below tax bracket 6 and above tax bracket 5.
  baseline_value: 0.35
 _II_rt7 : 0.45
  name: Personal income (regular/non-AMT/non-pass-through) tax rate 7
  desc: The tax rate applied to the portion of taxable income below tax
        bracket 7 and above tax bracket 6.
  baseline_value: 0.37
 _LLC_Expense_c : 0.0
  name: Lifetime learning credit expense limit
  desc: The maximum expense eligible for lifetime learning credit, per child.
  baseline_value: 10000.0
 _NIIT_rt : 0.0
  name: Net Investment Income Tax rate
  desc: If modified AGI exceeds _NIIT_thd, all net investment income is taxed
        at this rate.
  baseline_value: 0.038
 _PT_brk1 : [50000, 100000, 50000, 50000, 100000]
            ['single', 'joint', 'separate', 'headhousehold', 'widow']
  name: Pass-through income tax bracket (upper threshold) 1
  desc: Income from sole proprietorships, partnerships and S-corporations
        below this threshold is taxed at tax rate 1.
  baseline_value: [9714.55, 19429.1, 9714.55, 13870.64, 19429.1]
 _PT_brk2 : [50000, 100000, 50000, 50000, 100000]
            ['single', 'joint', 'separate', 'headhousehold', 'widow']
  name: Pass-through income tax bracket (upper threshold) 2
  desc: Income from sole proprietorships, partnerships and S-corporations
        below this threshold and above tax bracket 1 is taxed at tax rate 2.
  baseline_value: [39470.13, 78940.26, 39470.13, 52830.82, 78940.26]
 _PT_brk3 : [50000, 100000, 50000, 50000, 100000]
            ['single', 'joint', 'separate', 'headhousehold', 'widow']
  name: Pass-through income tax bracket (upper threshold) 3
  desc: Income from sole proprietorships, partnerships and S-corporations
        below this threshold and above tax bracket 2 is taxed at tax rate 3.
  baseline_value: [84141.75, 168283.5, 84141.75, 84141.75, 168283.5]
 _PT_brk4 : [50000, 100000, 50000, 50000, 100000]
            ['single', 'joint', 'separate', 'headhousehold', 'widow']
  name: Pass-through income tax bracket (upper threshold) 4
  desc: Income from sole proprietorships, partnerships and S-corporations
        below this threshold and above tax bracket 3 is taxed at tax rate 4.
  baseline_value: [160634.25, 321268.5, 160634.25, 160634.25, 321268.5]
 _PT_brk5 : [50000, 100000, 50000, 50000, 100000]
            ['single', 'joint', 'separate', 'headhousehold', 'widow']
  name: Pass-through income tax bracket (upper threshold) 5
  desc: Income from sole proprietorships, partnerships and S-corporations
        below this threshold and above tax bracket 4 is taxed at tax rate 5.
  baseline_value: [203980.0, 407960.0, 203980.0, 203980.0, 407960.0]
 _PT_brk6 : [50000, 100000, 50000, 50000, 100000]
            ['single', 'joint', 'separate', 'headhousehold', 'widow']
  name: Pass-through income tax bracket (upper threshold) 6
  desc: Income from sole proprietorships, partnerships and S-corporations
        below this threshold and above tax bracket 5 is taxed at tax rate 6.
  baseline_value: [509950.0, 611940.0, 305970.0, 509950.0, 509950.0]
 _PT_excl_rt : 0.0
  name: Pass-through income exclusion rate
  desc: Fraction of qualified business income excluded from taxable income.
  baseline_value: 0.2
 _PT_rt2 : 0.45
  name: Pass-through income tax rate 2
  desc: The second lowest tax rate, applied to the portion of income from sole
        proprietorships, partnerships and S-corporations below tax bracket 2
        and above tax bracket 1.
  baseline_value: 0.12
 _PT_rt3 : 0.45
  name: Pass-through income tax rate 3
  desc: The third lowest tax rate, applied to the portion of income from sole
        proprietorships, partnerships and S-corporations below tax bracket 3
        and above tax bracket 2.
  baseline_value: 0.22
 _PT_rt4 : 0.45
  name: Pass-through income tax rate 4
  desc: The tax rate applied to the portion of income from sole
        proprietorships, partnerships and S-corporations below tax bracket 4
        and above tax bracket 3.
  baseline_value: 0.24
 _PT_rt5 : 0.45
  name: Pass-through income tax rate 5
  desc: The third highest tax rate, applied to the portion of income from sole
        proprietorships, partnerships and S-corporations below tax bracket 5
        and above tax bracket 4.
  baseline_value: 0.32
 _PT_rt6 : 0.45
  name: Pass-through income tax rate 6
  desc: The second higher tax rate, applied to the portion of income from sole
        proprietorships, partnerships and S-corporations below tax bracket 6
        and above tax bracket 5.
  baseline_value: 0.35
 _PT_rt7 : 0.45
  name: Pass-through income tax rate 7
  desc: The highest tax rate, applied to the portion of income from sole
        proprietorships, partnerships and S-corporations below tax bracket 7
        and above tax bracket 6.
  baseline_value: 0.37
 _SS_percentage1 : 0.1
  name: Social Security taxable income decimal fraction 1